### ISSUE TITLE
Publications with keys as the sole treatments - GBIF

### ISSUE THREAD

**Issue by flsimoes** [plazi/learning#8]
Should publications which have only a key as a treatment be uploaded to GBIF?
Here's an example:
[Insecta Mundi 0719](https://drive.google.com/open?id=1sPl3cgUTXJt0MPiH-W6wije--Pp7aX5l)
UUID - 8B7AB316FF87FFA591652A523E6B9765

**Comment by myrmoteras** [comment]
yes.

**Comment by flsimoes** [comment]
OK, so I need to find out why this particular publication wasn't uploaded to GBIF.

I thought that, in order for that to happen, you would need materialsCitation and a DarwinCore.

Have you dealt with anything like this previously?

**Comment by myrmoteras** [comment]
You might also check the metadata which, if not complete, inhibit the upload.

The DWCA and other files have been added so we would now, wether images, or treatments have been discovred. You might as well disregard this. The only thing that is relevant, is whether with batch upload IMF do not upload, then you have to open them and find out. The first things is to check metadata. Then run it throug the QC tool and see whether you can discover a blocker error(s).

**Comment by flsimoes** [comment]
Metadata are fine (just double-checked it), the zenodo (https://zenodo.org/record/3674913#.Xk1L52hKgUF) and TB entries are a proof of that.

I think I've found the issue by running the QC tool, however I'm not sure how to handle it.
Basically, we are lacking a proper taxon name for the heading subSubSection (it should be Encyrtidae). I believe I need to add "encyrtids" as a `taxonomicName` and then write Encyrtidae in the attributes. What do you think?

![image](https://user-images.githubusercontent.com/3343086/74846591-79b8f200-530f-11ea-8591-bec118dbf074.png)

**Comment by myrmoteras** [comment]
I would just what you proposed and add all the higher taxa etc.

**Comment by flsimoes** [comment]
That did the trick!
Thanks!
